In [9]:
#Problem1:

import numpy as np
arr = np.arange(2,50,3)
print(arr)

[[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]]


In [18]:
# Problem 2:

l1 = []
l2 = []
print("Enter 5 elements in list1")
for i in range(5):
    num = int(input())
    l1.append(num)
print("Enter 5 elements in list2")
for i in range(5):
    num = int(input())
    l2.append(num)
arr1 = np.array(l1)
arr2 = np.array(l2)
print(arr1)
print(arr2)

#concatenate array

arr = np.concatenate((arr1,arr2))
print(arr)

#sort array

arr1 = np.sort(arr1)
arr2 = np.sort(arr2)
print(arr1)
print(arr2)
    

Enter 5 elements in list1
3
2
5
6
2
Enter 5 elements in list2
76
8
4
9
3
[3 2 5 6 2]
[76  8  4  9  3]
[ 3  2  5  6  2 76  8  4  9  3]
[2 2 3 5 6]
[ 3  4  8  9 76]


In [16]:
# Problem 3:

a1 = np.arange(3)
print(a1)
#[0 1 2]

a2 = np.arange(9).reshape(3,3)
print(a2)

#[[0 1 2]
# [3 4 5]
 #[6 7 8]]

a3 = np.arange(18).reshape(2,3,3)
print(a3)

#[[[ 0  1  2]
#[ 3  4  5]
#[ 6  7  8]]

# [[ 9 10 11]
#  [12 13 14]
#  [15 16 17]]]


print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

#1
#2
#3

print(a1.size)
print(a2.size)
print(a3.size)

#3
#9
#18

[0 1 2]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


1
2
3


3
9
18


In [17]:
#Problem 4:
a = np.arange(6).reshape(3, 2)
print(a)
# [[0 1]
#[2 3]
#[4 5]]
print(np.expand_dims(a, 0).shape)
# (1, 3, 2)

print(np.expand_dims(a, 1).shape)
# (3, 1, 2)




[[0 1]
 [2 3]
 [4 5]]
(1, 3, 2)
(3, 1, 2)
